### ISSUE TITLE
“Temperatus” can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by purplespider** [simonbs/Temperatus#3]
I'm getting this message after downloading the latest release ZIP, and trying to open the app:
![](http://spdr.me/2182+)

The error in the console is:

```
25/04/2014 11:47:52.710 CoreServicesUIAgent[51468]: Error SecAssessmentCreate: The operation couldn’t be completed. (OSStatus error -2147409652.)
```

Running OS X 10.9.2, and Gatekeeper is set to allow from "Anywhere".

**Comment by purplespider** [comment]
Did some more digging and it came up with `CSSMERR_TP_CERT_REVOKED` so looks like a certificate issue?

**Comment by simonbs** [comment]
Version 1.0.1 should be better. https://github.com/simonbs/Temperatus/releases/tag/1.0.1
